package('iotop') { action :install }
package('tree') { action :install }
package('htop') { action :install }
package('ncdu') { action :install }
package('jnettop') { action :install }
package('ranger') { action :install }
package('nmap') { action :install }
package('expect') { action :install }
package('multitail') { action :install }
package('dnsutils') { action :install }
package('nethogs') { action :install }
package('rxvt-unicode-terminfo') { action :install }
package('rsync') { action :install }
package('strace') { action :install }
package('the_silver_searcher') { action :install }
package('gvim') { action :install }
package('vim-systemd') { action :install }
