---
driver:
  name: docker
  use_sudo: false

busser:
  ruby_bindir: '/usr/bin'

provisioner:
  name: chef_zero
  chef_client_path: /usr/bin/chef-client

platforms:
  - name: arch
    driver_config:
      image: 'logankoester/archlinux-chef'
      platform: arch
      disable_upstart: true
      require_chef_omnibus: false
      provision_command:
        - pacman -S --noconfirm --needed supervisor git
        - rm /etc/gemrc
      run_command: 'sh -c "/usr/sbin/sshd -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes && /usr/sbin/supervisord -c /etc/supervisord.conf -n"'

suites:
  - name: default
    driver_config:
      hostname: default
    run_list:
      # Some of these recipes cannot run in a container, so
      # we cannot test them with the Docker driver.
      #
      #- 'recipe[archlinux::locale]'
      - 'recipe[archlinux::makeflags]'
      #- 'recipe[archlinux::static_network]'
      #- 'recipe[archlinux::hostname]'
      #- 'recipe[archlinux::haveged]'
      - 'recipe[archlinux::keyring]'
      - 'recipe[archlinux::pacman]'
      #- 'recipe[archlinux::cron]'
      #- 'recipe[archlinux::mlocate]'
      #- 'recipe[archlinux::chef]'
      - 'recipe[archlinux::pacaur]'
      - 'recipe[archlinux::packages]'
      - 'recipe[archlinux::ruby_shadow]'
      - 'recipe[archlinux::journald]'
    data_bags_path: 'test/integration/data_bags'
    #attributes:
    #  archlinux:
